name: Build & Deploy TorizonCore
on:
  - push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Build
        shell: pwsh
        run: |
          ./.vscode/tasks.ps1 run build-debug-local

      - name: Build Release
        shell: pwsh
        run: |
          ./.vscode/tasks.ps1 run publish-release-amd64

      - name: Release
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $_tag = Get-Content -Path ./VERSION
          zip -r "Torizon-WSL2-Welcome-$_tag.zip" ./bin/Release/net8.0/linux-x64/publish/
          gh release create `
            --target main $_tag `
            -t "Torizon WSL2 Welcome $_tag" `
            -n "Torizon WSL2 Welcome $_tag" `
            "Torizon-WSL2-Welcome-$_tag.zip"
